[project]
name = "mcp-tse"
version = "0.1.0"
description = "Tehran Stock Exchange MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.13",
    "mcp[cli]>=1.9.4",
]

[dependency-groups]
dev = [
    "ruff>=0.12.3",
]
